<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.10"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.10" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Components\Auth\LogIn.razor" />
      <AdditionalFiles Include="Components\Auth\Logout.razor" />
      <AdditionalFiles Include="Components\Auth\Register.razor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Services.Abstractions\Services.Abstractions.csproj" />
      <ProjectReference Include="..\Services\Services.csproj" />
    </ItemGroup>

</Project>
